apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.name }}-role-binding
  namespace: {{ $.Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.app.name }}
  namespace: argocd
roleRef:
  kind: Role
  name: {{ .Values.app.name }}-role
  apiGroup: rbac.authorization.k8s.io
