apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.app.name }}-role
  namespace: {{ $.Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods","configmaps","secrets"]
  verbs: ["get","list","watch"]
- apiGroups: ["argoproj.io"]
  resources: [ "*"]
  verbs: ["get","list","watch"]