apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-backupper-role
rules:
- apiGroups: [""]
  resources: ["pods","configmaps","secrets"]
  verbs: ["get","list","watch"]
- apiGroups: ["argoproj.io"]
  resources: [ "*"]
  verbs: ["get","list","watch"]