apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-backupper-role-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: argocd-backupper
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-backupper-role
  apiGroup: rbac.authorization.k8s.io
